### ISSUE TITLE
cmus name stays in title bar of terminal

### ISSUE THREAD

**Issue by Geyup** [cmus/cmus#300] opened 2015-07-02 07:26 UTC
Hi,

If I just open either ```urxvt``` or ```xterm``` and then type at the command line, ```cmus```, the titlebar then changes saying;

```cmus v2.7.0```

But if I close cmus with q then y and go back to the terminal the name still stays in the titlebar.

**Comment by flyingmutant** [comment] 2015-07-02 08:03
Duplicate of #135

**Closed by flyingmutant** 2015-07-02 08:03 UTC

**Comment by Geyup** [comment] 2015-07-03 01:04
Sorry for not seeing the other issue, I thought I looked... :(
