### ISSUE TITLE
Importing to Library failed.

### ISSUE THREAD

**Issue by aungthurhahein** [cmus/cmus#223] opened 2014-12-06 07:19 UTC
Version:2.5.0
Importing music from NTFS partition failed with msg said 'segmentation fault'.

**Comment by flyingmutant** [comment] 2015-01-16 10:09
Any updates on this one?

**Comment by hoodakaushal** [comment] 2015-01-16 13:50
I'll add that I had that too, with the apt-get version. Building from source has solved the issue.

**Comment by flyingmutant** [comment] 2015-01-16 14:06
OK, so the problem is probably already solved. Closing.

**Closed by flyingmutant** 2015-01-16 14:06 UTC
Labels: can not reproduce
