### ISSUE TITLE
Play all files in directory?

### ISSUE THREAD

**Issue by georgjaehnig** [cmus/cmus#524] opened 2016-09-17 13:27 UTC
Hi, I've looked already a while for this but couldn't find it:

It it possible in the file browser to play all files of an directory? Or simply, when playing one file, make cmus to play all next files of the same directory?

Cheers,
Georg

**Comment by mahkoh** [comment] 2016-09-17 16:35
This is a duplicate of #467.

**Closed** 2016-09-19 19:18 UTC
Labels: duplicate
