### ISSUE TITLE
Special Mp3 file freezes input handling when being played

### ISSUE THREAD

**Issue by castilma** [cmus/cmus#933] opened 2019-09-29 22:56 UTC
---

1) `uname -a`:
```
Linux arctic 5.2.14-artix1-1-ARTIX #1 SMP PREEMPT Tue Sep 10 21:38:47 UTC 2019 x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
```
I'm on artix. and it's actually version 2.8.0-2.

3) `cmus --plugins`:
```
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao

```
I found an mp3 file that makes cmus stop responding to user input, as soon as the file is being played. Except for Ctrl-C (which gives  the 'type :quit ...' message) nothing seems to get processed. Also the cpu usage increases.

It also messes with one line of the ui, when being played. The title seems to contain a  'M- '.

[head.txt](https://github.com/cmus/cmus/files/3668217/head.txt)
because of copyright reasons I uploaded the result of 
`$ head -c 40k <music.mp3 >head.txt`.
sha1sum: 
```
af7ce661b0c9ac02533eeadd79eb41667b2a02e1  head.txt
```

**Comment by Ashymad** [comment] 2019-10-20 15:09
Quite possibly a duplicate of https://github.com/cmus/cmus/issues/847

**Comment by pgaskin** [comment] 2024-09-23 02:37
Doesn't seem that way:

```
$ ffprobe -i head.mp3 -hide_banner -loglevel info |& xxd
00000000: 5b6d 7033 2040 2030 7835 3561 3432 3234  [mp3 @ 0x55a4224
00000010: 6631 3834 305d 2066 696c 6573 697a 6520  f1840] filesize 
00000020: 616e 6420 6475 7261 7469 6f6e 2064 6f20  and duration do 
00000030: 6e6f 7420 6d61 7463 6820 2867 726f 7769  not match (growi
00000040: 6e67 2066 696c 653f 290a 496e 7075 7420  ng file?).Input 
00000050: 2330 2c20 6d70 332c 2066 726f 6d20 2744  #0, mp3, from 'D
00000060: 6f77 6e6c 6f61 6473 2f68 6561 642e 6d70  ownloads/head.mp
00000070: 3327 3a0a 2020 4d65 7461 6461 7461 3a0a  3':.  Metadata:.
00000080: 2020 2020 6172 7469 7374 2020 2020 2020      artist      
00000090: 2020 2020 3a20 4869 6c6c 736f 6e67 0a20      : Hillsong. 
000000a0: 2020 2067 656e 7265 2020 2020 2020 2020     genre        
000000b0: 2020 203a 2057 6f72 7368 6970 0a20 2020     : Worship.   
000000c0: 2074 6974 6c65 2020 2020 2020 2020 2020   title          
000000d0: 203a 2048 6520 4973 204c 6f72 640a 2020   : He Is Lord.  
000000e0: 2020 616c 6275 6d20 2020 2020 2020 2020    album         
000000f0: 2020 3a20 556e 6265 6b61 6e6e 740a 2020    : Unbekannt.  
00000100: 2020 6461 7465 2020 2020 2020 2020 2020    date          
00000110: 2020 3a20 3230 3130 0a20 2020 2063 6f6d    : 2010.    com
00000120: 6d65 6e74 2020 2020 2020 2020 203a 2077  ment         : w
00000130: 7777 2e64 7664 7669 6465 6f73 6f66 742e  ww.dvdvideosoft.
00000140: 636f 6d0a 2020 2020 6330 2020 2020 2020  com.    c0      
00000150: 2020 2020 2020 2020 3a20 7777 772e 6476          : www.dv
00000160: 6476 6964 656f 736f 6674 2e63 6f6d 0a20  dvideosoft.com. 
00000170: 2020 2063 3120 2020 2020 2020 2020 2020     c1           
00000180: 2020 203a 2077 7777 2e64 7664 7669 6465     : www.dvdvide
00000190: 6f73 6f66 742e 636f 6d0a 2020 2020 6332  osoft.com.    c2
000001a0: 2020 2020 2020 2020 2020 2020 2020 3a20                : 
000001b0: 7777 772e 6476 6476 6964 656f 736f 6674  www.dvdvideosoft
000001c0: 2e63 6f6d 0a20 2020 2074 7261 636b 2020  .com.    track  
000001d0: 2020 2020 2020 2020 203a 2031 0a20 2020           : 1.   
000001e0: 206c 7972 6963 732d 6465 7520 2020 2020   lyrics-deu     
000001f0: 203a 200a 2020 2020 2020 2020 2020 2020   : .            
00000200: 2020 2020 2020 2020 3a20 4f68 2062 6c65          : Oh ble
00000210: 7373 6564 206c 616d 6220 6f6e 6365 2073  ssed lamb once s
00000220: 6c61 696e 0a20 2020 2020 2020 2020 2020  lain.           
00000230: 2020 2020 2020 2020 203a 2057 696c 6c20           : Will 
00000240: 7265 6967 6e20 666f 7265 7665 7220 6d6f  reign forever mo
00000250: 7265 0a20 2020 2020 2020 2020 2020 2020  re.             
00000260: 2020 2020 2020 203a 2048 6973 2068 616e         : His han
00000270: 6473 206f 6e63 6520 626f 756e 6420 6e6f  ds once bound no
00000280: 7720 7361 7665 0a20 2020 2020 2020 2020  w save.         
00000290: 2020 2020 2020 2020 2020 203a 204f 7572             : Our
000002a0: 2047 6f64 2077 696c 6c20 6e65 7665 7220   God will never 
000002b0: 6661 696c 0a20 2020 2020 2020 2020 2020  fail.           
000002c0: 2020 2020 2020 2020 203a 200a 2020 2020           : .    
000002d0: 2020 2020 2020 2020 2020 2020 2020 2020                  
000002e0: 3a20 4865 2069 7320 4c6f 7264 0a20 2020  : He is Lord.   
000002f0: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000300: 203a 2048 6520 6973 204c 6f72 640a 2020   : He is Lord.  
00000310: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000320: 2020 3a20 5369 6e67 7320 6d79 2073 6f75    : Sings my sou
00000330: 6c0a 2020 2020 2020 2020 2020 2020 2020  l.              
00000340: 2020 2020 2020 3a20 4865 2069 7320 4c6f        : He is Lo
00000350: 7264 0a20 2020 2020 2020 2020 2020 2020  rd.             
00000360: 2020 2020 2020 203a 2041 6e64 2048 6520         : And He 
00000370: 6c69 7665 730a 2020 2020 2020 2020 2020  lives.          
00000380: 2020 2020 2020 2020 2020 3a20 5965 7320            : Yes 
00000390: 4865 206c 6976 6573 0a20 2020 2020 2020  He lives.       
000003a0: 2020 2020 2020 2020 2020 2020 203a 2049               : I
000003b0: 276d 2061 6c69 7665 2027 6361 7573 6520  'm alive 'cause 
000003c0: 4a65 7375 7320 6c69 7665 730a 2020 2020  Jesus lives.    
000003d0: 2020 2020 2020 2020 2020 2020 2020 2020                  
000003e0: 3a20 0a20 2020 2020 2020 2020 2020 2020  : .             
000003f0: 2020 2020 2020 203a 2027 5469 7320 6174         : 'Tis at
00000400: 2074 6865 2063 726f 7373 206f 6620 4368   the cross of Ch
00000410: 7269 7374 0a20 2020 2020 2020 2020 2020  rist.           
00000420: 2020 2020 2020 2020 203a 2057 6865 7265           : Where
00000430: 2065 6172 7468 2061 6e64 2068 6561 7665   earth and heave
00000440: 6e20 6d65 6574 0a20 2020 2020 2020 2020  n meet.         
00000450: 2020 2020 2020 2020 2020 203a 2057 6865             : Whe
00000460: 7265 2073 696e 2069 7320 6f76 6572 636f  re sin is overco
00000470: 6d65 0a20 2020 2020 2020 2020 2020 2020  me.             
00000480: 2020 2020 2020 203a 2054 6f20 476f 6420         : To God 
00000490: 7468 6520 7669 6374 6f72 790a 2020 2020  the victory.    
000004a0: 2020 2020 2020 2020 2020 2020 2020 2020                  
000004b0: 3a20 0a20 2020 2020 2020 2020 2020 2020  : .             
000004c0: 2020 2020 2020 203a 2041 6e64 206e 6f77         : And now
000004d0: 200a 2020 2020 2020 2020 2020 2020 2020   .              
000004e0: 2020 2020 2020 3a20 4c65 7420 7468 6520        : Let the 
000004f0: 6561 7274 6820 7265 736f 756e 6420 7769  earth resound wi
00000500: 7468 2070 7261 6973 650a 2020 2020 2020  th praise.      
00000510: 2020 2020 2020 2020 2020 2020 2020 3a20                : 
00000520: 466f 7220 6f75 7220 5361 7669 6f75 7220  For our Saviour 
00000530: 476f 6420 4865 2072 6569 676e 730a 2020  God He reigns.  
00000540: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000550: 2020 3a20 4865 2069 7320 6869 6768 2061    : He is high a
00000560: 6e64 206c 6966 7465 6420 7570 0a20 2020  nd lifted up.   
00000570: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000580: 203a 2041 7269 7365 0a20 2020 2020 2020   : Arise.       
00000590: 2020 2020 2020 2020 2020 2020 203a 2046               : F
000005a0: 6f72 2074 6865 204b 696e 6720 6f66 2067  or the King of g
000005b0: 6c6f 7279 2077 6169 7473 0a20 2020 2020  lory waits.     
000005c0: 2020 2020 2020 2020 2020 2020 2020 203a                 :
000005d0: 2048 6520 6973 2063 6f6d 696e 6720 6261   He is coming ba
000005e0: 636b 2061 6761 696e 0a20 2020 2020 2020  ck again.       
000005f0: 2020 2020 2020 2020 2020 2020 203a 2020               :  
00000600: 0a20 2020 2020 2020 2020 2020 2020 2020  .               
00000610: 2020 2020 203a 200a 2020 2020 2020 2020       : .        
00000620: 2020 2020 2020 2020 2020 2020 3a20 2050              :  P
00000630: 6f77 6572 6564 2062 7920 4c79 7269 6357  owered by LyricW
00000640: 696b 6920 2868 7474 703a 2f2f 6c79 7269  iki (http://lyri
00000650: 6373 2e77 696b 6961 2e63 6f6d 2f61 7069  cs.wikia.com/api
00000660: 2e70 6870 3f61 6374 696f 6e3d 7175 6572  .php?action=quer
00000670: 7926 7072 6f70 3d72 6576 6973 696f 6e73  y&prop=revisions
00000680: 2672 7670 726f 703d 636f 6e74 656e 7426  &rvprop=content&
00000690: 666f 726d 6174 3d78 6d6c 2674 6974 6c65  format=xml&title
000006a0: 733d 290a 2020 2020 616c 6275 6d5f 6172  s=).    album_ar
000006b0: 7469 7374 2020 2020 3a20 4869 6c6c 736f  tist    : Hillso
000006c0: 6e67 0a20 2020 2069 6433 7632 5f70 7269  ng.    id3v2_pri
000006d0: 762e 574d 2f4d 6564 6961 436c 6173 7350  v.WM/MediaClassP
000006e0: 7269 6d61 7279 4944 3a20 5c78 6263 7d60  rimaryID: \xbc}`
000006f0: 5c78 6431 235c 7865 335c 7865 324b 5c78  \xd1#\xe3\xe2K\x
00000700: 3836 5c78 6131 485c 7861 342a 2844 5c78  86\xa1H\xa4*(D\x
00000710: 3165 0a20 2020 2069 6433 7632 5f70 7269  1e.    id3v2_pri
00000720: 762e 574d 2f4d 6564 6961 436c 6173 7353  v.WM/MediaClassS
00000730: 6563 6f6e 6461 7279 4944 3a20 5c78 3030  econdaryID: \x00
00000740: 5c78 3030 5c78 3030 5c78 3030 5c78 3030  \x00\x00\x00\x00
00000750: 5c78 3030 5c78 3030 5c78 3030 5c78 3030  \x00\x00\x00\x00
00000760: 5c78 3030 5c78 3030 5c78 3030 5c78 3030  \x00\x00\x00\x00
00000770: 5c78 3030 5c78 3030 5c78 3030 0a20 2020  \x00\x00\x00.   
00000780: 2069 6433 7632 5f70 7269 762e 5065 616b   id3v2_priv.Peak
00000790: 5661 6c75 653a 205c 7866 665c 7837 665c  Value: \xff\x7f\
000007a0: 7830 305c 7830 300a 2020 2020 6964 3376  x00\x00.    id3v
000007b0: 325f 7072 6976 2e41 7665 7261 6765 4c65  2_priv.AverageLe
000007c0: 7665 6c3a 2073 365c 7830 305c 7830 300a  vel: s6\x00\x00.
000007d0: 2020 4475 7261 7469 6f6e 3a20 3030 3a30    Duration: 00:0
000007e0: 353a 3238 2e37 382c 2073 7461 7274 3a20  5:28.78, start: 
000007f0: 302e 3032 3330 3231 2c20 6269 7472 6174  0.023021, bitrat
00000800: 653a 2030 206b 622f 730a 2020 5374 7265  e: 0 kb/s.  Stre
00000810: 616d 2023 303a 303a 2041 7564 696f 3a20  am #0:0: Audio: 
00000820: 6d70 332c 2034 3830 3030 2048 7a2c 2073  mp3, 48000 Hz, s
00000830: 7465 7265 6f2c 2066 6c74 702c 2032 3032  tereo, fltp, 202
00000840: 206b 622f 730a 2020 2020 4d65 7461 6461   kb/s.    Metada
00000850: 7461 3a0a 2020 2020 2020 656e 636f 6465  ta:.      encode
00000860: 7220 2020 2020 2020 2020 3a20 4c41 4d45  r         : LAME
00000870: 332e 3938 720a 2020 2020 5369 6465 2064  3.98r.    Side d
00000880: 6174 613a 0a20 2020 2020 2072 6570 6c61  ata:.      repla
00000890: 7967 6169 6e3a 2074 7261 636b 2067 6169  ygain: track gai
000008a0: 6e20 2d20 2d31 332e 3130 3030 3030 2c20  n - -13.100000, 
000008b0: 7472 6163 6b20 7065 616b 202d 2075 6e6b  track peak - unk
000008c0: 6e6f 776e 2c20 616c 6275 6d20 6761 696e  nown, album gain
000008d0: 202d 2075 6e6b 6e6f 776e 2c20 616c 6275   - unknown, albu
000008e0: 6d20 7065 616b 202d 2075 6e6b 6e6f 776e  m peak - unknown
000008f0: 2c20 0a20 2053 7472 6561 6d20 2330 3a31  , .  Stream #0:1
00000900: 3a20 5669 6465 6f3a 206d 6a70 6567 2028  : Video: mjpeg (
00000910: 4261 7365 6c69 6e65 292c 2079 7576 6a34  Baseline), yuvj4
00000920: 3230 7028 7063 2c20 6274 3437 3062 672f  20p(pc, bt470bg/
00000930: 756e 6b6e 6f77 6e2f 756e 6b6e 6f77 6e29  unknown/unknown)
00000940: 2c20 3338 3478 3238 382c 2039 306b 2074  , 384x288, 90k t
00000950: 6272 2c20 3930 6b20 7462 6e20 2861 7474  br, 90k tbn (att
00000960: 6163 6865 6420 7069 6329 0a20 2020 204d  ached pic).    M
00000970: 6574 6164 6174 613a 0a20 2020 2020 2063  etadata:.      c
00000980: 6f6d 6d65 6e74 2020 2020 2020 2020 203a  omment         :
00000990: 204f 7468 6572 0a                         Other.
```

The metadata is ASCII.

Nevertheless, I cannot reproduce this issue by playing `head.mp3` on the latest version of cmus, so I'm going to close this issue.

If this is still a problem, please re-open the issue with a few backtraces from gdb when this happens.

**Closed by pgaskin** 2024-09-23 02:37 UTC
