### ISSUE TITLE
Seeking in long mp3s is slow and very CPU intensive

### ISSUE THREAD

**Issue by mahkoh** [cmus/cmus#100] opened 2014-01-31 12:15 UTC
Probably because of libmad. Switch to libmpg123 to fix this issue.

**Comment by flyingmutant** [comment] 2015-03-03 16:22
As discussed on #104, we probably won't switch from libmad anytime soon. So — closing as `wontfix` for now.

**Closed by flyingmutant** 2015-03-03 16:22 UTC

**Comment by mahkoh** [comment] 2015-10-30 23:10
I'm listening to some longer mp3s right now (>2h) and seeking in them is really annoying. E.g., if you hold the right key pressed, it will continue to seek for a time proportional to the amount of time you keep the key pressed after you've let go of the key. This can cause cmus to "overseek" for several minutes when I try to skip a song.

If you don't want to maintain both plugins, then maybe we can just switch to mpg123 and drop libmad?

**Comment by flyingmutant** [comment] 2015-10-31 11:38
The problem is not the maintenance on my part — the problem is that this change may cause regressions for people, mostly for the sake of speeding up the seeking (are there any other real benefits?).

However, I like the fact that mpg123 is actively developed (and new libout123 thing might even help with #331), while libmad seems to be stagnant (stable?) for 10+ years.

OK, after some meditation I think we can give it a try. Can you please resubmit #104 with my comments addressed, and with as much feature parity with libmad as possible? Let's not completely drop libmad just now though.

If everything goes well, I can make a beta release with mpg123 being default, and, if everything goes well again, change the default in the next release.

**Comment by mahkoh** [comment] 2016-03-07 16:16
I've changed my mind. Instead of adding a new plugin, the problem can also be solved by simply deleting the libmad plugin. Then cmus uses ffmpeg for mp3s which supports fast seeking.
