### ISSUE TITLE
Warnings ruin the interface

### ISSUE THREAD

**Issue by xrisk** [cmus/cmus#436] opened 2016-04-17 14:46 UTC
So, I just installed cmus on OS X using MacPorts and it emits these warnings which ruin the curses UI.
Here's a screenshot.

<img width="802" alt="screen shot 2016-04-17 at 8 14 02 pm" src="https://cloud.githubusercontent.com/assets/10669859/14587896/00a766c2-04d9-11e6-9044-af5c9e003c4c.png">

Any way to remove them?
By the way, cmus is really great! 😁

---

1) `uname -a`:
```
Darwin null.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.7.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2013 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /opt/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  mikmod:
    Priority: 40
    File Types: mod s3m xm it 669 amf dsm far med mtm stm ult
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: ac3 aif aifc aiff ape au mka shn tta wma aac fla flac m4a m4b mp+ mp2 mp3 mp4 mpc mpp ogg wav wv
    MIME Types:

Output Plugins: /opt/local/lib/cmus/op
  ao

```

**Comment by bigfatgreg** [comment] 2016-04-18 15:53
i am getting this too

- uname -a
```
Darwin ____.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```
- cmus --version
```
cmus v2.4.3
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2011 Various Authors
```
- cmus --plugins
```
Input Plugins: /usr/local/Cellar/cmus/2.4.3/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
```

**Comment by ixjlyons** [comment] 2016-04-18 17:33
Seems to be a duplicate of #331.

You should be able to work around the interference with the the interface by redirecting stderr:

```
cmus 2>/dev/null
```

**Comment by flyingmutant** [comment] 2016-04-18 20:29
Yeah, this is a duplicate of #331.
If you install `HEAD` version of cmus, you can use CoreAudio output, which does not have this warning.
There is no official release with CoreAudio plugin yet, though.

**Closed by flyingmutant** 2016-04-18 20:29 UTC
