### ISSUE TITLE
(aarch64, cmus v.2.7) segmentation fault > several mp4

### ISSUE THREAD

**Issue by mrkapqa** [cmus/cmus#964] opened 2020-04-10 15:28 UTC
---

segmentation fault upon playing mp4 in folder

some play, most give "segmentation fault"

1) `uname -a`:
```
Linux rock64 4.4.213-rockchip64 #18 SMP Sat Mar 28 17:52:26 CET 2020 aarch64 aarch64 aarch64 GNU/Linux



```

2) `cmus --version`:
```
2.7.0
```

3) `cmus --plugins`:
```
cmus --plugins
Input Plugins: /usr/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  cdio:
    Priority: 50
    File Types:
    MIME Types: x-content/audio-cdda
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  ffmpeg:
    Priority: 30
    File Types: aa ac3 aif aifc aiff ape au mka shn tak tta wma webm aac fla flac m4a m4b mp+ mp2 mp3 mp4 mpc mpp ogg wav wv
    MIME Types:

Output Plugins: /usr/lib/cmus/op
  pulse
  alsa
  jack
  ao

```

**Comment by nefthy** [comment] 2020-04-10 19:44
2.7.0 is quite old. please check if you can reproduce with 2.8.0 or even better git head.

**Comment by pgaskin** [comment] 2021-06-03 03:56
I'm going to close this issue since there hasn't been a response for over a year. @mrkapqa, feel free to reopen it if you can reproduce this issue with v2.9.1 or later.

**Closed by pgaskin** 2021-06-03 03:56 UTC
