### ISSUE TITLE
a bitrate conversion bug

### ISSUE THREAD

**Issue by ct1ee** [cmus/cmus#788] opened 2018-03-27 09:55 UTC
---

Only noise occur when playing flac files whose samplerate are higher(like 96KHz/24bit) than macOS system setting in Audio MIDI Setup.app(44.1KHz).
1) `uname -a`:
```
(Darwin mac 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64)
```

2) `cmus --version`:
```
(cmus v2.8.0-rc0-87-g20a738d)
```

3) `cmus --plugins`:
```
(Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  coreaudio
)
```

**Comment by nefthy** [comment] 2019-02-05 12:14
```lang=c
	// Now try to see if the device support our format sample rate.
	// For some high quality media samples, the frame rate may exceed
	// device capability. In this case, we let CoreAudio downsample
	// by decimation with an integer factor ranging from 1 to 4.
```
Hm, decimation probably isn't the best choice. @Wang-Yue is there any other option we could use?

**Comment by nefthy** [comment] 2019-02-05 12:15
@ct1ee is the noise like a hiss on top of the normal audio or do you only here noise?

**Comment by nefthy** [comment] 2019-02-11 17:37
probably duplicate of #584

**Closed by nefthy** 2019-02-11 17:37 UTC
Labels: coreaudio, flac, input plugin
