### ISSUE TITLE
Save/Load queue

### ISSUE THREAD

**Issue by Q3CPMA** [cmus/cmus#657] opened 2017-03-12 18:38 UTC
Hello, I think it would make sense for `save -q <file>` to have a corresponding `load -q <file>`.

**Comment by mahkoh** [comment] 2017-03-12 18:40
Duplicate of #462

**Closed by mahkoh** 2017-03-12 18:40 UTC

**Comment by Q3CPMA** [comment] 2017-03-12 18:51
Well, my question isn't really about saving, but loading back.
