### ISSUE TITLE
cmus using deprecated Carbon Component Manager on OSX? 

### ISSUE THREAD

**Issue by bimmlerd** [cmus/cmus#345] opened 2015-10-22 08:29 UTC
I'm on El Capitan, and for some mp3 tracks I get the following warning plastered all over:

`2015-10-22 09:19:51.203 cmus[18584:3270880] 09:19:51.203 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.`

Happy to provide more info if needed.

**Comment by flyingmutant** [comment] 2015-10-22 09:34
Thanks for reporting! This is a duplicate of #331, though. Closing.

**Closed by flyingmutant** 2015-10-22 09:34 UTC

**Comment by bimmlerd** [comment] 2015-10-22 09:36
Derp, very sorry about that. Thanks.
