### ISSUE TITLE
High bit/sample rate FLAC produces noise on macOS with both ao and CoreAudio

### ISSUE THREAD

**Issue by LeftyBC** [cmus/cmus#584] opened 2016-11-22 23:47 UTC
High bitrate FLAC files produce nothing but noise on my macOS 10.11.6 machine using Cmus from HEAD (both 90722a0 and c5af200) installed via Homebrew.

`brew install --HEAD --with-ffmpeg` was used to install.

44KHz/16bit FLACs play fine, 96KHz/24bit FLACs produce nothing but noise.

Have tried setting 
```
 dsp.coreaudio.enable_hog_mode true
 dsp.coreaudio.sync_sample_rate true
```
with no luck.

Have also tried using ao driver as output.  With CoreAudio, the noise is quite choppy, with ao it's still noise but it's much less choppy.

Have tried setting ffmpeg priority higher than FLAC so it will play the files, but I still get noise.

These files play back fine on a Linux box with cmus, using Foobar2000 on Windows, as well as with VOX on the Mac, so the files appear to be valid.cv

Github won't let me attach an example as they're >80MB, so I've uploaded one to my webserver at https://lefty.tv/stuff/Nirvana%20-%20In%20Utero%20-%2020th%20Anniversary%20Super%20Deluxe%20-%2001%20-%20Serve%20The%20Servants%20(Album%20Version).flac

SHA256 (Nirvana - In Utero - 20th Anniversary Super Deluxe - 01 - Serve The Servants (Album Version).flac) = 884db526ac1514c44fac05f650006cba6c65b03551d275a283e4e289513107df

```
$ metaflac --show-bps --show-sample-rate Nirvana\ -\ In\ Utero\ -\ 20th\ Anniversary\ Super\ Deluxe\ -\ 01\ -\ Serve\ The\ Servants\ \(Album\ Version\).flac
24
96000
```

Converting the file to Apple Lossless using XLD seems to allow it to play fine with Cmus.

Please let me know if I can provide any extra information.

---

1) `uname -a`:
```
Darwin eav1046337m.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.8.0-rc0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/HEAD-c5af200_1/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/HEAD-c5af200_1/lib/cmus/op
  coreaudio
  ao
```

**Comment by nefthy** [comment] 2016-11-23 02:03
file works fine for me with the flac/jack plugins.

**Comment by mahkoh** [comment] 2016-11-23 02:21
Ping @Wang-Yue

**Comment by Wang-Yue** [comment] 2016-11-23 04:15
Cannot reproduce. 

I don't have problem playing the file you gave. The file plays pretty fine, and cmus produces identical sound compared to VOX.app. 

I also tried all the files from Sony's hi-res samples. You can get the files here:

http://helpguide.sony.net/high-res/sample1/v1/en/index.html

I tried both 88.2/24 and 96/24. I used laptop internal speaker, and also tried external DAC. No issues at all.

My setup:


```
20:14:10 ~ $ cmus --version
cmus v2.8.0-rc0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
20:14:16 ~ $ cmus --plu
Input Plugins: /usr/local/lib/cmus/ip
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  coreaudio
```

**Comment by Wang-Yue** [comment] 2016-11-23 04:36
I ran into this paticular problem while switching from 16bit track to 24bit one, or skipping a 24 bit track, and I reported that problem here. After I submit the fix in https://github.com/cmus/cmus/commit/e0df2065cdb311336c576f9783d09ad1c674e898 I never ran into such issue since then. 

The noise is usually caused by two potential problems 

- the endianness is wrong.
- one or two byte in 24 bit is missing. so the data is not aligned correctly. 

If you have time to debug, check whether the following buffers are identical 

- the `mdata` in https://github.com/cmus/cmus/blob/master/op/coreaudio.c#L271
- the `buf` in  https://github.com/cmus/cmus/blob/master/op/coreaudio.c#L722
- flac -d foo.flac, get the wav file, and examine the data beginning from offset 44. 

make sure the endianness is correct.

**Comment by LeftyBC** [comment] 2016-11-23 07:36
Will check that when I'm at work tomorrow and see if I can provide any insight on buffer differences.

**Comment by LeftyBC** [comment] 2016-11-23 22:56
I'm just setting up to do this testing, but in the meantime I tried both starting with a 44KHz file then skipping to a 96KHz, or starting with a 96KHz file directly, and it was the same noise in both scenarios.

**Comment by Wang-Yue** [comment] 2016-11-23 23:41
Again I'm not able to reproduce. Do other mac users have the same issue?

If people cannot reproduce the problem you have, unfortunately you'll have to debug yourself.

**Comment by LeftyBC** [comment] 2016-11-23 23:41
I'm just learning LLDB right now to attempt to debug :)

**Comment by Wang-Yue** [comment] 2016-11-23 23:44
In this case, you can write the hex value of the buffer to a local file (or, you can d_print to cmus-debug.log), so you don't need to learn LLDB. If you start fresh to play a 96/24 file and it has the problem, then you'll just need to test this scenario.

**Comment by Wang-Yue** [comment] 2016-11-26 10:34
if you can't provide further information, I'll ask the maintainer to close this bug. 

Also according to your description, flac with old ao plugin also has the same problem, so I assume it also presents in previous versions. So it shouldn't block the current release.

**Comment by nefthy** [comment] 2016-11-26 14:24
Is the hardware capable of playing audio at 24bit? Does OSX convert to lower bit rates if this is not the case?

**Comment by Wang-Yue** [comment] 2016-11-26 17:44
> Is the hardware capable of playing audio at 24bit?

Macs produced since 2012 has 24bit dacs built in.

> Does OSX convert to lower bit rates if this is not the case?

In Audio and Midi Setup, users can choose the desired channel/bit/samplerate settings for a DAC. As we are output to a AudioUnit (a CoreAudio HAL abstraction), CoreAudio will automatically do the bit/channel/sample rate conversion. If the channel/bit/samplerate are the same between system setting and media file, no conversion will be made (so it's bit perfect in this case).

**Comment by Wang-Yue** [comment] 2016-11-29 00:21
Please close this bug. It can be reopened when it has the exact details, or other people are experiencing it.

**Comment by LeftyBC** [comment] 2016-11-29 22:20
Sorry for the late reply, I haven't been able to figure out with my limited C debugging skills what the issue with buffers is.  I've got a workaround for now (converting to ALAC) so when I get a little more proficient with lldb I'll reopen.

**Comment by jtl999** [comment] 2018-06-20 19:18
I have the issue as noted by the OP.

2015 Macbook Pro running OS X 10.11.6.

cmus HEAD installed via homebrew

```
jtl-macbookpro:~ jtl$ cmus --version
cmus 17bf542
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

```
jtl-macbookpro:~ jtl$ cmus --plugins
Input Plugins: /usr/local/Cellar/cmus/HEAD-17bf542_2/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/HEAD-17bf542_2/lib/cmus/op
  coreaudio
  ao
```

Sound device is a Fiio E10K (USB), which supports 96khz/24bit audio.

![](https://i.imgur.com/B5e6vPN.png)

If I have the sample rate set to 16/44 and I play a higher resolution file I get the static. But if I have the sample rate set at max (24/96) and I play a 16/44 FLAC there is no static. Also no static when the audio device is at 24/96 and I play a 24/96 FLAC.

I would be willing to privately send some audio files to the cmus maintainer which exhibit this issue and one's that don't.

I could try the buffer testing later.

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment] 2018-07-24 14:02
Same issue

**Comment by jtl999** [comment] 2018-08-14 18:36
OK.

Changed `OSStatus coreaudio_play_callback` in `coreaudio.c` to look like this.

```
static OSStatus coreaudio_play_callback(void *user_data,
                    AudioUnitRenderActionFlags *flags,
                    const AudioTimeStamp *ts,
                    UInt32 busnum,
                    UInt32 nframes,
                    AudioBufferList *buflist)
{
    d_print("%x\n", buflist->mBuffers[0].mData);
    int count = nframes * coreaudio_format_description.mBytesPerFrame;
    buflist->mBuffers[0].mDataByteSize = coreaudio_ring_buffer_read(&coreaudio_ring_buffer,
                                    buflist->mBuffers[0].mData,
                                    count);
    return noErr;
}
```

and changed `static int coreaudio_write` in `coreaudio.c` to look like this.

```
static int coreaudio_write(const char *buf, int cnt)
{
    d_print("%x\n", buf);
    return coreaudio_ring_buffer_write(&coreaudio_ring_buffer, buf, cnt);
}
```

Testing with a 24-96khz FLAC file of my choosing. I'd download one of the Sony test files but I'm on vacation on a data limited mobile connection.

With the internal speakers set to 16-44.1khz in Audio MIDI Setup (which causes the static noise)

```
coreaudio_fill_format_description: Bits:24
coreaudio_write: 8893000
coreaudio_play_callback: 7a81cc00
coreaudio_play_callback: 7a81cc00
coreaudio_write: 889b000
coreaudio_write: 88a2008
coreaudio_play_callback: 7a81cc00
coreaudio_play_callback: 7a81cc00
coreaudio_write: 88a3008
coreaudio_play_callback: 7a81cc00
coreaudio_play_callback: 7a81cc00
coreaudio_write: 88ab008
coreaudio_write: 88b1010
coreaudio_play_callback: 7a81cc00
coreaudio_play_callback: 7a81cc00
[sic]
```

With the internal speakers set to 32-96khz in Audio MIDI Setup (no static noise and sound is normal)
```
coreaudio_fill_format_description: Bits:24
coreaudio_write: 773c000
coreaudio_play_callback: 81034800
coreaudio_write: 7744000
coreaudio_play_callback: 81034800
coreaudio_write: 774a000
coreaudio_write: 774b008
coreaudio_play_callback: 81034800
coreaudio_write: 7750008
coreaudio_play_callback: 81034800
coreaudio_write: 7756008
coreaudio_write: 775a010
coreaudio_play_callback: 81034800
coreaudio_write: 775c010
coreaudio_play_callback: 81034800
coreaudio_write: 7762010
coreaudio_play_callback: 81034800
coreaudio_write: 7768010
coreaudio_write: 7769018
coreaudio_play_callback: 81034800
coreaudio_write: 776e018
coreaudio_play_callback: 81034800
coreaudio_write: 7774018
coreaudio_write: 7778020
coreaudio_play_callback: 81034800
coreaudio_write: 777a020
coreaudio_play_callback: 81034800
coreaudio_write: 7780020
coreaudio_play_callback: 81034800
coreaudio_write: 7786020
coreaudio_write: 7787028
coreaudio_play_callback: 81034800
coreaudio_write: 778c028
coreaudio_play_callback: 81034800
coreaudio_write: 7792028
```

Both tests were done with the same file.

**Comment by Wang-Yue** [comment] 2018-08-14 19:29
you are merely printing the buf pointer, not the actual buffer. 

Currently I do not plan to work on cmus any further as the core developer is no longer actively maintaining the project --- 2.8 has been postponed for 2 years, and it seems that this project will eventually die. If you want to use a terminal based music player on Mac OS X, I recommend MPD, whose CoreAudio output was also written by me.

**Comment by jtl999** [comment] 2018-08-14 19:31
*facepalm*

I'll take a look at printing the actual buffer value later.

That's a shame about cmus being abandoned.

**Comment by jtl999** [comment] 2018-08-15 17:13
I figured out how to read individual samples of the mData buffer.

```
UInt32 *audiodata = buflist->mBuffers[0].mData;
d_print("%X\n", audiodata[1]);
```

Testing with a 44.1khz 2000hz "tone" flac I generated in Audacity.

```
flac_open: sr: 44100, ch: 1, bits: 24
ip_setup: pcm convert: scale=1 convert=0 convert_in_place=0
coreaudio_play_callback: C6BF64D8
coreaudio_play_callback: 88761C4D
coreaudio_play_callback: 49149FA6
coreaudio_play_callback: BD31D78D
coreaudio_play_callback: D0E35B74
coreaudio_play_callback: 50E33383
coreaudio_play_callback: 2DB7AAC8
coreaudio_play_callback: B7B6C22B
coreaudio_play_callback: DCE34DBC
coreaudio_play_callback: B21473C
coreaudio_play_callback: EA0BBAE3
coreaudio_play_callback: 7FF0B065
coreaudio_play_callback: A5FD3B7A
coreaudio_play_callback: 929D56CD
coreaudio_play_callback: 4833CF06
coreaudio_play_callback: CC7BA345
coreaudio_play_callback: 783D25C0
coreaudio_play_callback: 58ED614C
coreaudio_play_callback: EAE2E606
coreaudio_play_callback: 1789B8F
coreaudio_play_callback: BCF30DD1
coreaudio_play_callback: 25AA661D
coreaudio_play_callback: 61FBFE8A
coreaudio_play_callback: 2AC199B5
coreaudio_play_callback: E5C0F514
coreaudio_play_callback: 19B064F7
coreaudio_play_callback: 3FDE1724
coreaudio_play_callback: FB3A9DD5
```

```
jtl-macbookpro:~ jtl$ cat cmus-debug.txt |grep 49149FA6
coreaudio_play_callback: 49149FA6
coreaudio_play_callback: 49149FA6
coreaudio_play_callback: 49149FA6
coreaudio_play_callback: 49149FA6
```

(You can see the sample repeat as I restart the file and it gets to the same position.

I'll do more testing later.

**Comment by jtl999** [comment] 2018-08-15 20:09
First off I should start by saying I'm not a programmer with much experience with audio programming unfortunately but I did some tests anyway and it's something I'm interested in as a future thing to study.

Patch to dump samples of `mData` to cmus-debug.log in hexidecimal notation (not just dumping the memory address like a derp)

```
diff --git a/op/coreaudio.c b/op/coreaudio.c
index f968eed..1c1bdcb 100644
--- a/op/coreaudio.c
+++ b/op/coreaudio.c
@@ -266,6 +266,11 @@ static OSStatus coreaudio_play_callback(void *user_data,
                                        UInt32 nframes,
                                        AudioBufferList *buflist)
 {
+    UInt32 *audiodata = buflist->mBuffers[0].mData;
+    for (int i = 0; i < nframes; i++) {
+        d_print("%X\n", audiodata[i]);
+    }
+
        int count = nframes * coreaudio_format_description.mBytesPerFrame;
        buflist->mBuffers[0].mDataByteSize = coreaudio_ring_buffer_read(&coreaudio_ring_buffer,
```

I have two files I tested with, a 2000Hz tone generated at 16/44.1 in FLAC and a 2000hz tone generated at 24/96 in FLAC 

# First test. Soundcard set to 16/44.1 playing the 16/44.1 2000hz tone FLAC (No noise)

```
file_changed: file: /Users/jtl/Music/Tone.flac
metadata_cb: VORBISCOMMENT
tell_cb:
flac_open: sr: 44100, ch: 1, bits: 24
ip_setup: pcm convert: scale=1 convert=0 convert_in_place=0
coreaudio_fill_format_description: Bits:24
coreaudio_set_channel_position: Cannot set the channel layout successfully.
coreaudio_play_callback: 0
coreaudio_play_callback: 40000000
coreaudio_play_callback: 5FA80000
coreaudio_play_callback: 800007FA
coreaudio_play_callback: FB
coreaudio_play_callback: FC
coreaudio_play_callback: FD
coreaudio_play_callback: FE
coreaudio_play_callback: DF
coreaudio_play_callback: E0
coreaudio_play_callback: E1
coreaudio_play_callback: E2
coreaudio_play_callback: E3
coreaudio_play_callback: E4
coreaudio_play_callback: E5
coreaudio_play_callback: E6
coreaudio_play_callback: E7
coreaudio_play_callback: E8
[sic]
```

Let me pick a sample that occurs within the first second of the file (using `watch -n 0.1 tail ~/cmus-debug.log`, pausing after the first second)

`coreaudio_play_callback: 1839146B`

When we grep it, we can see it occur multiple times, which makes sense, because this is a 2000hz constant tone.

```
jtl-macbookpro:~ jtl$ grep 1839146B cmus-debug.txt
coreaudio_play_callback: 1839146B
coreaudio_play_callback: 1839146B
coreaudio_play_callback: 1839146B
coreaudio_play_callback: 1839146B
coreaudio_play_callback: 1839146B
coreaudio_play_callback: 1839146B
coreaudio_play_callback: 1839146B
coreaudio_play_callback: 1839146B
```

# Test: Play the same 2000hz tone at 16/44.1khz with the soundcard set to 32/96khz (No noise)

```
jtl-macbookpro:~ jtl$ grep 1839146B cmus-debug.txt
coreaudio_play_callback: 1839146B
coreaudio_play_callback: 1839146B
coreaudio_play_callback: 1839146B
```

All good here.

# Next test: Play the 2000hz tone file at 24/96khz with the soundcard set to 32/96khz (works with no noise)

Pick a sample from `cmus-debug.log` again.

`coreaudio_play_callback: 16F08D17`

Good, after about 4 seconds in we see the sample occurred 3 times, and I restarted the file and pause at approximately the same position.

```
jtl-macbookpro:~ jtl$ grep 16F08D17 cmus-debug.txt
coreaudio_play_callback: 16F08D17
coreaudio_play_callback: 16F08D17
coreaudio_play_callback: 16F08D17
coreaudio_play_callback: 16F08D17
coreaudio_play_callback: 16F08D17
coreaudio_play_callback: 16F08D17
```

# Next test: Play the 2000hz tone file at 24/96khz with the soundcard set to 16/44.1khz (noise)

Tone sounds like it's "pulsing" due to the noise caused by the "bug". we grep the log

```
jtl-macbookpro:~ jtl$ grep 16F08D17 cmus-debug.txt |wc -l
       0
```

No results.

**Comment by jtl999** [comment] 2018-09-25 19:57
Was bored. Made another patch to `op/coreaudio.c` to print the `buf` buffer in `coreaudio_write`

```
diff --git a/op/coreaudio.c b/op/coreaudio.c
index f968eed..92a9366 100644
--- a/op/coreaudio.c
+++ b/op/coreaudio.c
@@ -266,6 +266,11 @@ static OSStatus coreaudio_play_callback(void *user_data,
                                        UInt32 nframes,
                                        AudioBufferList *buflist)
 {
+    UInt32 *audiodata = buflist->mBuffers[0].mData;
+    for (int i = 0; i < nframes; i++) {
+        d_print("%X\n", audiodata[i]);
+    }
+
        int count = nframes * coreaudio_format_description.mBytesPerFrame;
        buflist->mBuffers[0].mDataByteSize = coreaudio_ring_buffer_read(&coreaudio_ring_buffer,
                                                                        buflist->mBuffers[0].mData,
@@ -717,8 +722,12 @@ static int coreaudio_drop(void)
        return OP_ERROR_SUCCESS;
 }

-static int coreaudio_write(const char *buf, int cnt)
+// Change variable type of constructor to ensure values match when comparing buffers
+
+static int coreaudio_write(const UInt32 *buf, int cnt)
 {
+
+    d_print("%X\n", *buf);
        return coreaudio_ring_buffer_write(&coreaudio_ring_buffer, buf, cnt);
 }
```

Testing with my "tone" files again that I used above (I can supply on request)

# First test. Soundcard set to 16/44.1 playing the 16/44.1 2000hz tone FLAC (No noise)

If I grep for the exact value in `cmus-debug.log` that I used last time (1839146B) it shows as the value in some of the `coreaudio_play_callback` calls but not `coreaudio_write`.

Let's try something else.

```
jtl-macbookpro:~ jtl$ grep BDDEA2F6 cmus-debug.txt
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_write: BDDEA2F6
```

Good.

# Test: Play the same 2000hz tone at 16/44.1khz with the soundcard set to 32/96khz (No noise)

I don't see the same `coreaudio_write` call with the same value (BDDEA2F6), but I do see the coreaudio_play_callback call(s).

```
jtl-macbookpro:~ jtl$ grep BDDEA2F6 cmus-debug.txt
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
coreaudio_play_callback: BDDEA2F6
```

# Next test: Play the 2000hz tone file at 24/96khz with the soundcard set to 16/44.1khz (noise)

```
jtl-macbookpro:~ jtl$ grep BDDEA2F6 cmus-debug.txt |wc -l
       0
```

No results.

Also, anyone have any good development guides for CoreAudio or audio programming in general. I personally don't have much experience with this area.

**Comment by nev4eh8959** [comment] 2018-12-09 02:15
After setting softvol to false fixed the problem for me.

**Comment by Berulacks** [comment] 2018-12-12 13:08
I'm having the same issue with a locally compiled version of `master`. When using `coreaudio` as an output plugin, with `softvol` set to `true`, any 24 bit FLAC file just produces a jarring intermittent static sound. Hurt my ears with headphones on.

**Comment by lxcode** [comment] 2020-07-05 20:47
For me, the issue happened initially with softvol off on MacOS — turning it on and putting it to 100 fixed it for some files, but on another album it blasted *extremely* loud noise into my headphones. Honestly, this problem makes cmus actually dangerous to use with the coreaudio plugin.

**Comment by pgaskin** [comment] 2021-06-04 10:20
I'm going to close this issue since it's over 4 years old and it's unclear where the bug actually is and if these comments are even referring to the same bug. Feel free to open new issues if you still have reproducible problems with specific FLAC files on the latest version of cmus.

**Closed by pgaskin** 2021-06-04 10:20 UTC
Labels: bug

**Comment by MayCXC** [comment] 2022-05-12 22:39
I think I can reproduce this, with the current cmus from `brew` on an M1 macbook installed with `brew`. .flac files have bursts of extremely noisey hissing, while an mp3v0 of the same recording sounds fine. I can mess with audio outputs this weekend.

cmus also makes a lot of noise for a dead program ;)

**Comment by madskjeldgaard** [comment] 2022-09-23 11:53
> I can reproduce this, with the current cmus from `brew` on an M1 macbook. .flac files have bursts of extremely noisey hissing, while an mp3v0 of the same recording sounds fine. I can mess with audio outputs this weekend.
> 
> cmus also makes a lot of noise for a dead program ;)

Same here

**Comment by madskjeldgaard** [comment] 2022-09-23 11:56
For me the quick and dirty fix is to simply raise the sample rate of the system to be higher than that of the file, in case anyone was wondering.

**Comment by lxcode** [comment] 2022-11-08 17:42
Can confirm, bumping it up to max in Audio Midi Setup seems to fix the issue. Thanks!

**Comment by dragonattheend** [comment] 2022-12-15 09:24
> Can confirm, bumping it up to max in Audio Midi Setup seems to fix the issue. Thanks!

I raised it to 96khz, but still get a white noise from certain files. Same files play no problem in VLC...

**Comment by lxcode** [comment] 2022-12-17 14:14
Yeah, after testing for a few weeks I still have problems with some files as well. :-/ Using [termusic](https://github.com/tramhao/termusic) for the moment.

**Comment by dragonattheend** [comment] 2022-12-20 04:13
I switched softvol to false as suggested above. 

The problem now is that music is loud on minimum in my headphones and not as loud through speakers :) 

But I really prefer cmus to ncmpcpp/musikcube... I tried termusic, but it's not my cup of tea either..

**Comment by skatkov** [comment] 2024-02-02 12:31
I'm having similar issues,  converted files to mp3 and they sound just fine.
