### ISSUE TITLE
[Arch] cmus command output nothing

### ISSUE THREAD

**Issue by Alaanor** [cmus/cmus#368] opened 2015-12-06 00:51 UTC
Hi,

I really want to try cmus. So I do a simple `sudo pacman -S cmus` (Install cmus and dependencies).

And now when I type cmus in terminal (XTerm):

    [user@laptop ~]$ cmus
     

Nothing other, no panel. (Just a "\n" and waiting the ctrl+c) I am missing something ?

`man cmus-tutorial` said:
> just type cmus in a terminal and press Enter

package installed: libcue-1.4.0-4 libdiscid-0.6.1-2 cmus-2.7.1-2.

I already tried to use an another terminal (like xfce4-terminal and gnome-terminal) and tried to use the git version on AUR.

**Comment by flyingmutant** [comment] 2015-12-06 12:12
Hi @Alaanor, thanks for reporting. This looks like a duplicate of #337, let's track it there.

**Closed by flyingmutant** 2015-12-06 12:12 UTC
