### ISSUE TITLE
Cmus not responding any keybindings

### ISSUE THREAD

**Issue by niltonvasques** [cmus/cmus#234] opened 2015-01-09 19:33 UTC
Hi guys,

Yesterday cmus became unresponsive to any keybindinds, so I cannot change views( 1~7 keys ), cannot play music, cannot manage queue and do nothing using keybindings.
However command-line option it works well, so I can type : , and manage cmus for command line.

Firstly I am was using version 2.4 from debian\wheezy repository. So I am try uninstall this version and install v2.5.0 from debian\jessie repository, but cmus continues unresponsive. And finally I am try too install release v2.6.0 from sources, but unfortunately same error happen. :(

There is any way that I can debug cmus to understand what's can happen?

**Comment by flyingmutant** [comment] 2015-01-09 21:04
Can you please rename your `~/.cmus/autosave` and `~/.cmus/rc` files to something else, to see if this can be caused by messed up settings?

**Comment by niltonvasques** [comment] 2015-01-10 03:47
Thanks a lot flyingmutant! 
I just renamed ~/cmus/autosave and everything went back to works fine!
However I don't remember of change any settings of cmus this week. Maybe I just pressed some combination of keys that messed up my cmus settings.
Do you know what can be happened ?
It is my ~/cmus/autosave: http://paste.debian.net/139994/

**Comment by flyingmutant** [comment] 2015-01-10 06:57
For some reason, your auto save file lacked all the bind settings. This was a known issue, which I believe is fixed now -- but for you, upgrading did not help, because it did not change the content of the auto save file. Renaming it triggers regeneration from default settings though.

**Closed by flyingmutant** 2015-01-10 06:57 UTC

**Comment by niltonvasques** [comment] 2015-01-10 16:52
Thanks again!
Do you know the version that it issue was fixed?

**Comment by flyingmutant** [comment] 2015-01-10 17:58
Sorry, I don't really remember. Using git master is always a good idea though :-)
