### ISSUE TITLE
compiling error cygwin64

### ISSUE THREAD

**Issue by buzzbo** [cmus/cmus#343] opened 2015-10-21 00:25 UTC
I am compiling from source on Cygwin x86_64, after running `./configure` then `make`:

```
   CC     ape.o
In file included from ape.c:23:0:
xmalloc.h: In function 'xstrndup':
xmalloc.h:79:2: error: implicit declaration of function 'strndup' [-Werror=implicit-function-declaration]
  char *s = strndup(str, n);
  ^
xmalloc.h:79:12: warning: incompatible implicit declaration of built-in function 'strndup'
  char *s = strndup(str, n);
            ^
cc1: some warnings being treated as errors
scripts/lib.mk:66: recipe for target 'ape.o' failed
make: *** [ape.o] Error 1
```

If I find a solution I'll post it. [This](https://stackoverflow.com/questions/9168150/implicit-declaration-of-strndup) is as close as I get but it's a warning not an error.

**Comment by flyingmutant** [comment] 2015-10-21 09:39
Can you please see if https://github.com/flyingmutant/cmus/commit/8ab9abe42e605b8a2aced5c761554afdaa13747e fixes the issue? You'll need to run `./configure` again, of course.

**Comment by buzzbo** [comment] 2015-10-21 16:56
I get the same error after that patch.

**Comment by buzzbo** [comment] 2015-10-22 00:09
I found [this thread](https://stackoverflow.com/questions/11561261/how-to-compile-without-warnings-being-treated-as-errors) on stackexchange which suggested removing the -Werror cflag, so I did that (removed -Werror-implicit-function-declaration) and `make` succeeded. Cmus is working for me.

**Comment by myselfganu** [comment] 2015-10-23 11:56
Hi buzzbo,

I am getting the same error while make. can you please, elaborate, how you did that (removing the -Werror cflag). Not able to understand the stackexchange thread that you have provided. 

Thank you.

**Comment by maggick** [comment] 2015-10-23 14:22
Hi, I recently (more or less now) wrote an article about compiling cmus in cygwin with mp3 support. I update the article about a month ago.
http://matthieukeller.com/2015/01/compiling-cmus-for-cygwin.html

**Comment by buzzbo** [comment] 2015-10-23 14:58
@myselfganu not sure this is kosher but after running ./configure, I edited config.mk and deleted `-Werror-implicit-function-declaration` from the CFLAGS line.

@maggick I actually used your guide to install libmad when I put cmus on my laptop a couple months ago. It was very helpful! Sadly my laptop crashed. Happily, I installed Mint 17.2 mate, but my laptop is old and sluggish. I recently was trying to get cmus going on my work computer when I ran into the strndup error, but aforementioned fix seems to work. You may want to add that to your guide. It could be my version of cygwin or gcc or something causing the warnings to be treated as errors. Not really sure. I just try to get by but I never had a programmer's brain.

**Comment by mahkoh** [comment] 2015-10-23 15:09
>but aforementioned fix seems to work

It's not a fix.. An implicit function declaration is almost always incorrect. Add this to the top of the offending files:

```c
char *strndup(const char *s, size_t n);
```

**Comment by myselfganu** [comment] 2015-10-23 16:25
@maggick same like @buzzbo, i arrived at this error by following the steps from your post. First of all thanks for the post. I was able to get till here with its help. A tiny correction will be great, it will make it the document for windows(via cygwin).

@mahkoh thanks for the fix (i have edited xmalloc.h), installed cmus and am listening my first track, on cmus :smile:.

@buzzbo thank you for your reply.

Cheers.

**Comment by buzzbo** [comment] 2015-10-24 17:36
OK sounds like things are all good.

**Comment by maggick** [comment] 2015-10-26 12:32
I will update the post this evening. Thank you guys for your inputs and your feedback.

**Comment by maggick** [comment] 2015-10-29 07:35
I have upload the post:
http://matthieukeller.com/2015/01/compiling-cmus-for-cygwin.html

@mahkoh, @myselfganu is the fix correct (I never had this error, so impossible for me to test it)?

**Comment by myselfganu** [comment] 2015-10-29 08:19
@maggick yes, the fix worked for me. Checked the post, looks fine to me.Thanks for updating the post.

**Comment by maggick** [comment] 2015-10-29 12:56
okay great, thanks you all :)

**Comment by flyingmutant** [comment] 2015-10-29 13:01
I'll reopen this, since cmus should compile as-is, without requiring extra patching.

**Comment by bambams** [comment] 2016-01-23 07:31
I was installing cmus into a new Cygwin setup today. Ran into this from the pu branch. Is there no fix yet or has it just not been rebased onto pu?

**Comment by flyingmutant** [comment] 2016-02-02 19:45
It is not clear yet what is the correct fix for this issue, and while this is the case, you'll have to use workarounds, unfortunately.

**Comment by buzzbo** [comment] 2016-02-25 05:58
@maggick @mahkoh I have a new machine and am trying to compile again and when I add

```c
char *strndup(const char *s, size_t n);
```
to the top of `xmalloc.h`, run `make`, I get a new error:

       CC     ape.o
       CC     browser.o
       CC     buffer.o
    In file included from buffer.c:20:0:
    xmalloc.h:19:30: error: unknown type name 'size_t'
     char *strndup(const char *s, size_t n);
                                  ^
    In file included from buffer.c:20:0:
    xmalloc.h: In function 'xstrndup':
    xmalloc.h:80:12: error: implicit declaration of function 'strndup' [-Werror=implicit-function-declaration]
      char *s = strndup(str, n);
                ^
    xmalloc.h:80:12: warning: incompatible implicit declaration of built-in function 'strndup'
    cc1: some warnings being treated as errors
    scripts/lib.mk:66: recipe for target 'buffer.o' failed
    make: *** [buffer.o] Error 1

I'm good at following directions but not debugging. Thanks.

**Comment by maggick** [comment] 2016-02-25 09:20
@buzzbo This time it is not `ape.o` who failed but `buffer.o`. The error is linked to the type `size_t` which is unknown.
I will take a further look at it this weekend.

**Comment by buzzbo** [comment] 2016-02-25 15:36
@maggick Thanks again.

**Comment by buzzbo** [comment] 2016-02-28 16:19
Update!
I got it to compile by adding:
```c
#include <stddef.h>
```
to the following files `buffer.h
comment.h
discid.h
id3.h
tabexp.h
xstrjoin.h
path.h
xmalloc.h`

But in `xmalloc.h` I guess I had to put it above ```c char *strndup(const char *s, size_t n); ```.

It compiled OK but I did get a lot of warnings, example below.

```make
mixer_oss.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from mixer_oss.c:22:0:
xmalloc.h:20:7: warning: redundant redeclaration of 'strndup' [-Wredundant-decls]
 char *strndup(const char *s, size_t n);
       ^
In file included from /usr/include/string.h:10:0,
                 from channelmap.h:22,
                 from op.h:23,
                 from mixer_oss.c:20:
/usr/include/string.h:86:8: note: previous declaration of 'strndup' was here
 char  *_EXFUN(strndup,(const char *, size_t));
        ^

```

**Comment by maggick** [comment] 2016-02-28 18:45
I compiled cmus with a fresh cygwin install and the last development version of cmus (`git clone https://github.com/cmus/cmus`) without any problem this afternoon. I got support for both flac and mp3 files (using libmad).
There is a lot of missing cygwin dependencies in my article.

Neverthe less I have not been able to reproduce the bug. Be sure to add the line `char *strndup(const char *s, size_t n);` in `xmalloc.h` between the last include and the first function declaration.

**Comment by pgaskin** [comment] 2024-09-20 06:43
It looks like cmus currently compiles properly with cygwin:

```bash
$ curl -s https://mirror.csclub.uwaterloo.ca/cygwin/x86_64/release/cmus/cmus-2.11.0-3-src.tar.xz | tar xOJf - cmus-2.11.0-3.src/cmus.cygport
# cmus.cygport
NAME="cmus"
VERSION=2.11.0
RELEASE=3
SUMMARY="cmus is a small, fast and powerful console music player for Unix-like operating systems."
DESCRIPTION="cmus is a lightweight ncurses music player. It supports various output methods by using dynamically-loaded output plugins."
CATEGORY="Audio"
LICENSE="GPL-2.0"

HOMEPAGE="https://cmus.github.io/"
SRC_URI="https://github.com/cmus/cmus/archive/v${VERSION}.tar.gz"
SRC_DIR="cmus-${VERSION}"

# not found even when installing libmp4v2-devel libmp4v2_2

# libavcodec61, libavformat brings ffmpeg that has clang that has gcc as dependency
# libmodplug is deprecated
#
# # vorbis is missing from cmus --plugins, even with CONFIG_VORBIS?
BUILD_REQUIRES="libncurses-devel libmad-devel libvorbis-devel flac-devel libopusfile-devel libsamplerate-devel libwavpack-devel libao-devel libcdio_paranoia-devel libmpcdec-devel libcddb-devel libdiscid-devel"
REQUIRES="libncursesw10 libmad0 libvorbis flac libopusfile0 libsamplerate0 libwavpack1 libao libcdio_paranoia2 libmpcdec7 libcddb libdiscid"

PKG_NAMES="cmus"

src_compile() {
	lndirs
	cd ${B}

	sh ./configure \
		CONFIG_MAD=y CONFIG_VORBIS=y CONFIG_FLAC=y CONFIG_OPUS=y CONFIG_MPC=y CONFIG_WAVPACK=y CONFIG_CDDB=y CONFIG_CDIO=y \
		CONFIG_PULSE=n \
		prefix=/usr bindir=/usr/bin libdir=/usr/lib datadir=/usr/share mandir=/usr/share/man

	cygmake
}
```

**Closed by pgaskin** 2024-09-20 06:43 UTC
Labels: bug
