### ISSUE TITLE
Crash trying to read High Definition Track

### ISSUE THREAD

**Issue by Lagrang3** [cmus/cmus#833] opened 2018-10-27 13:01 UTC
Hi everyone. 
I am get this error (in the stderr):

```
ip_read: BUG: rc % (((((((ip->data.sf))) & 0x00000038 ) >> 0) >> 3) * ((((ip->data.sf)) & 0xff000000 ) >> 24)) != 0
```

and cmus crashes when trying to read a high definition track of 24bit-96kHz surround (6 channels). 
The same track plays well on vlc and quodlibet.

1) `uname -a`:
```
Linux COSMOS 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0-rc0-91-ga0bfeb5
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  pulse
  roar
  alsa
  sndio
  jack
  ao
```

**Comment by jtl999** [comment] 2018-10-28 19:53
What format is the track?

**Comment by Lagrang3** [comment] 2018-10-29 17:38
Oh, sorry I forgot to mention. The track is encoded in FLAC.

**Comment by Lagrang3** [comment] 2018-11-06 05:42
@jtl999 Thanks for the reply, here https://transfer.sh/Hh8Uc/file.flac

**Comment by nefthy** [comment] 2019-02-05 14:51
duplicate of #644

**Closed by nefthy** 2019-02-05 14:51 UTC
Labels: bug, duplicate
