### ISSUE TITLE
spectrum analyzer

### ISSUE THREAD

**Issue by sedrubal** [cmus/cmus#336] opened 2015-09-22 17:10 UTC
Is it possible to provide a spectrum analyzer / music visualization like open cubic player? :smile: 

![ocp](https://cloud.githubusercontent.com/assets/5571650/10025637/7276e09a-615d-11e5-8ab3-ecb9eb67aedc.png)

**Comment by luzpaz** [comment] 2015-10-24 13:19
:+1:

**Comment by sedrubal** [comment] 2015-10-24 13:27
Another project is [cava](https://github.com/karlstav/cava).

Maybe one can steal code from them :P

**Comment by da-edra** [comment] 2016-11-03 23:27
That would make it perfect.

**Comment by pgaskin** [comment] 2021-06-03 04:54
Duplicate of #112.

**Closed by pgaskin** 2021-06-03 04:54 UTC
Labels: feature request
