### ISSUE TITLE
Random sequence always the same on Cygwin

### ISSUE THREAD

**Issue by garncarz** [cmus/cmus#146] opened 2014-07-08 21:44 UTC
```
$ cmus --version
cmus v2.5.0
```

Although random generated by BASH differs between restarts:

```
$ echo $RANDOM
21277
```

```
$ echo $RANDOM
17761
```

**Comment by maggick** [comment] 2015-03-05 15:19
I confirm the issue, after track A will always come track B in shuffle mod (even after closing and reopening the program and even in a new cygwin instance.)
Should I make a new issue ?

**Comment by flyingmutant** [comment] 2015-03-05 16:16
Is this for Cygwin only, or not?

**Comment by garncarz** [comment] 2015-03-05 16:26
As for me, yes.

**Comment by flyingmutant** [comment] 2015-03-05 16:29
@maggick, you have `:set auto_reshuffle=true`, and it is not working also?

**Comment by garncarz** [comment] 2015-03-05 16:32
Maybe it should be noted that in my case Cygwin is running on top of Win XP.

**Comment by maggick** [comment] 2015-03-06 09:08
It is not in `~/.cmus/rc` but in `~/.config/cmus/autosave` but yes I got the `auto_reshuffle` at true.

    $ grep shuffle ~/.config/cmus/autosave
    set auto_reshuffle=true
    set shuffle=true
    bind common s toggle shuffle

As said @garncarz it works as excepted when I run `:shuffle`.

I would test it on arch linux this evening.

**Comment by maggick** [comment] 2015-03-07 22:53
I confirm that this is only for cygwin.
On arch linux with the package version (pacman -Ss cmus) I got the right behavior.

**Comment by flyingmutant** [comment] 2015-03-08 16:18
Thanks for confirming this is Cygwin-only issue. This is super weird, though. Looking at code ([`shuffle_list_reshuffle`](https://github.com/cmus/cmus/blob/master/track.c#L312) and [`shuffle_track_init`](https://github.com/cmus/cmus/blob/master/track.c#L281)) there is absolutely nothing suspicious. Cmus is calling `rand` for each of the tracks — I can not imagine `rand` returning the same number every time it is called.

**Comment by garncarz** [comment] 2015-03-08 20:24
Probably the seed is the same everytime the program is started. Maybe calling the reshuffling function automatically during the start would solve this issue?

**Comment by flyingmutant** [comment] 2015-03-09 08:48
@garncarz the thing is, reshuffling is not working *during the program is running*. Successive calls to `rand()` should return different values regardless of the seed.

**Comment by garncarz** [comment] 2015-04-10 21:59
I just tried the version 2.6.0, the bug unfortunately stays.

**Comment by flyingmutant** [comment] 2015-04-12 10:24
If somebody can help with this — it will be appreciated. I have no Windows/Cygwin at hand, so I can not reproduce and debug this issue.

**Comment by garncarz** [comment] 2015-04-12 10:26
Ok, I can try, do you have some hint on how to start, please?

**Comment by flyingmutant** [comment] 2015-04-12 10:34
Try to add some `d_print()`s in [shuffle_list_reshuffle](https://github.com/cmus/cmus/blob/master/track.c#L312) and its uses maybe (the output will appear in `~/cmus-debug.txt`).

**Comment by flyingmutant** [comment] 2015-04-12 10:35
Also, [shuffle_list_add](https://github.com/cmus/cmus/blob/master/track.c#L286) is the one calling [shuffle_track_init](https://github.com/cmus/cmus/blob/master/track.c#L281), which is calling `rand()`.

**Comment by garncarz** [comment] 2015-04-26 23:09
So far (with the help of a commit mentioned above) I've observed that songs are really assigned with the same rand values, although `rand()` run before returns changing results.

Run 1:
```
main: charset = 'UTF-8'
player_init: could not set real-time scheduling priority: Not supported
lib_init: srand
cmus_init: rand: 0.564666
player_set_op: setting op to 'waveout'
init_plugin: initialized pcm for waveout
init_curses: Number of supported colors: 8
init_curses: ts: 0 fs: 0
shuffle_track_init: Yes Sir, I Can Boogie 0.690001
TIMER: worker job:           0.001794
shuffle_add: Yes Sir, I Can Boogie
shuffle_track_init: Yes Sir, I Can Boogie 0.505418
...
```

Run 2:
```
main: charset = 'UTF-8'
player_init: could not set real-time scheduling priority: Not supported
lib_init: srand
cmus_init: rand: 0.005879
player_set_op: setting op to 'waveout'
init_plugin: initialized pcm for waveout
init_curses: Number of supported colors: 8
init_curses: ts: 0 fs: 0
shuffle_track_init: Yes Sir, I Can Boogie 0.690001
TIMER: worker job:           0.001851
shuffle_add: Yes Sir, I Can Boogie
shuffle_track_init: Yes Sir, I Can Boogie 0.505418
...
```

I also tried gdb and noticed this:
```
(gdb) tty /dev/pty2
(gdb) run
Starting program: /home/Ondra/git/cmus/cmus.exe
[New Thread 1356.0x2408]
[New Thread 1356.0x142c]
[New Thread 1356.0x2150]
[New Thread 1356.0xc68]
[New Thread 1356.0x1814]
[New Thread 1356.0x9ac]
[New Thread 1356.0x109c]
[New Thread 1356.0x16dc]
[New Thread 1356.0x1fa4]
```

Maybe that `srand` call hasn't affected a thread responsible for shuffling? (Btw. do we really need that many threads?)

**Comment by flyingmutant** [comment] 2015-04-27 08:43
This indeed may be the case! Can you please try to add `srand(time(NULL))` before [this line](https://github.com/cmus/cmus/blob/master/worker.c#L56)?

BTW, I misunderstood this issue a bit — I was thinking that `auto_reshuffle` logic is not working (it should kick in after shuffle list reaches the end), which is not the case. The issue is that shuffle list *at startup only* is always the same, right?

P.S. I believe that cmus only creates 3 threads: producer, consumer and worker – just grep for `pthread_create`.

**Comment by garncarz** [comment] 2015-04-27 15:30
Great job, flyingmutant! Now it works correctly.

(Yes, you're right, it's a startup thing, I haven't observed reaching a shuffle list end.)

**Closed** 2015-04-27 15:41 UTC
Labels: bug

**Comment by mahkoh** [comment] 2015-04-27 15:45
https://msdn.microsoft.com/en-us/library/f0d4wb4t.aspx

>The srand function sets the starting point for generating a series of pseudorandom integers in the current thread.

From what I understand, POSIX also leaves the behavior of rand and srand in multi-threaded programs unspecified and provides rand_s to fix this.

**Comment by maggick** [comment] 2015-04-28 07:45
just recompile cmus, no more issue.
Well done.
