### ISSUE TITLE
can't clear playlist

### ISSUE THREAD

**Issue by chenjie199234** [cmus/cmus#1001] opened 2020-11-16 15:17 UTC
---

1) `uname -a`:
```
archlinux 5.9.8-arch1-1 #1 SMP PREEMPT Tue,10 Nov 2020 22:44:11 +0000 x86_64 GNU/Linux
```

2) `cmus --version`:
```
2.8.0
```

3) `cmus --plugins`:
```
none
```

clear command can't clear playlist

**Comment by sklv** [comment] 2020-11-21 01:16
Did you select the playlist by hitting `enter`?
I tried to reproduce this, and initially thought that it wasn't working, but once I selected a playlist with `enter`, `cmus-remote -c` successfully cleared it.

**Comment by pgaskin** [comment] 2020-12-12 22:17
I can't reproduce this issue either.

**Comment by pgaskin** [comment] 2021-03-01 03:53
I'm going to close this issue since there hasn't been a response for 3 months. Feel free to comment/reopen this with instructions to reproduce the issue.

**Closed by pgaskin** 2021-03-01 03:53 UTC

**Comment by findmarbles** [comment] 2022-02-02 12:30
I am on version 2.8.0 as well and can recreate the problem mentioned by OP.
```
cmus-remote -P somefile.mp3
cmus-remote -P -c

```
won't work, because as ghost mentioned in the playlist view the track of the playlist instead of the playlist itself is highlighted.
Neither did my rc file when I added `clear -p` as an option, probably for the same reason.

A workaround is:
```
cmus-remote -P somefile.mp3
cmus-remote -P -C win-next
cmus-remote -P -c
```
