### ISSUE TITLE
Mouse: mouse_scroll_down not working

### ISSUE THREAD

**Issue by mist** [cmus/cmus#254] opened 2015-02-21 16:53 UTC
Scrolling up with the mouse moves up but scrolling down doesn't do anything.
In vim it works, so my terminal seems to be configured correctly. I checked my cmus config and deleted it to reset everything but still no results.

I'm using `v2.6.0-75-ge3bab2a` inside `screen` inside `URxvt` on `Debian/testing`.

BTW: Great work with the mouse support!

**Comment by flyingmutant** [comment] 2015-02-22 16:52
@pavel-belikov in #147 [claims](https://github.com/cmus/cmus/pull/147#issuecomment-49769974) that this is caused by old ncurses. Can you please check if that is indeed the case?

**Comment by mist** [comment] 2015-02-22 18:20
I've got ncurses [5.9+20140913](https://packages.debian.org/jessie/ncurses-bin) installed which seams to be way newer than the [thread linked to](http://lists.gnu.org/archive/html/bug-ncurses/2012-01/msg00012.html) in #147.

**Comment by flyingmutant** [comment] 2015-02-22 19:14
I can not reproduce the issue (on OS X though). What are the values for `mouse_scroll_down` and `mouse_scroll_up` in cmus' settings (7) view?

**Comment by mist** [comment] 2015-02-22 19:20
I'm not on my computer right now but it did make sense, I think it was win-up and win-down.

**Comment by pavel-belikov** [comment] 2015-02-23 07:16
I've recently updated to Debian Jessie and I can reproduce it. It seems that scrolling down isn't reported at all.

**Comment by mist** [comment] 2015-02-26 14:06
Is there anything else I can test to figure out where the problem is and maybe file a bug against ncurses in the Debian Bugtracker?

**Comment by flyingmutant** [comment] 2015-02-27 13:18
@pavel-belikov can you please confirm if this is a ncurses bug, not a cmus one?

**Comment by pavel-belikov** [comment] 2015-02-27 18:47
I can't say for sure. Mouse wheel doesn't work in htop, scroll down doesn't work in aptitude. Ncurses demo `mouse-menu` doesn't work at all.
The problem is I don't see if there is mouse wheel scroll down support in ncurses without `--enable-ext-mouse`. There is no `BUTTON5_CLICKED` event.

**Comment by flyingmutant** [comment] 2015-08-26 12:58
@mist – any news about this issue?

**Comment by mist** [comment] 2015-08-26 13:09
No news, everything is still the same.
Scrolling up works, scrolling down doesn't. But yeah, in aptitude scrolling down doesn't do anything either while scrolling up is like clicking.

**Comment by flyingmutant** [comment] 2015-08-26 13:11
Thanks! I'm closing this issue since there appears to be no clear way to proceed. Feel free to reopen though.

**Closed by flyingmutant** 2015-08-26 13:11 UTC
Labels: bug

**Comment by hgroll** [comment] 2016-03-05 11:29
Scrolling works for me with v2.7.1 when holding down CTRL button. Maybe this helps.

**Comment by mist** [comment] 2016-03-05 15:15
I can confirm that

**Comment by idontcar3** [comment] 2016-03-18 02:58
I can confirm that too, same issue here

Scroll down won't work UNLESS CTRL is pressed
`root@mbastic:~# ncurses5-config --version
6.0.20151024
root@mbastic:~# ncursesw5-config --version
6.0.20151024
root@mbastic:~# cmus --version
cmus v2.7.1`

**Comment by VanAxe** [comment] 2016-06-15 17:10
Same here, scroll down will not work unless CTRL is held.

`ncurses= 5.9.20150214`
`cmus= v2.7.0-91-gfdce44b`
`uname= Linux 4.5.6-200.fc23.x86_64`

**Comment by mahkoh** [comment] 2016-06-15 17:53
debian does not build ncurses with support for 5 buttons. Complain [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=230990) if you want this to change.

**Comment by VanAxe** [comment] 2016-06-15 18:31
Do you know where I can do the same for Fedora?

**Comment by sbmkvp** [comment] 2017-07-10 15:09
Clicking the middle button scrolls down as well!
