### ISSUE TITLE
Unexpected behavior & segfault when adding two particular albums

### ISSUE THREAD

**Issue by ploopkazoo** [cmus/cmus#417] opened 2016-03-19 09:14 UTC
There exist two very similar albums (same artist, similar album titles, similar track listing). When adding either of these albums to cmus, there is no issue. However, when adding _both_ of them, only one shows up in the library, and upon attempting to quit, cmus segfaults without writing relevant information to cmus-debug.txt.

List of files in the two albums, with slight filename differences highlighted:
![list_highlighted](https://cloud.githubusercontent.com/assets/15199487/13897701/47c61076-ed91-11e5-93f4-1a04dd1c21bd.png)

cmus after attempting to add both albums, showing only one in the library:
![cmus](https://cloud.githubusercontent.com/assets/15199487/13897650/8ffe5932-ed8e-11e5-85e5-4491080b5d90.png)

Segfault upon quitting cmus:
![segfault](https://cloud.githubusercontent.com/assets/15199487/13897654/9ea8d516-ed8e-11e5-8806-12f3a2337c88.png)
I have been able to reproduce this on Ubuntu (cmus v2.5.0) and Parabola (v2.7.1 and v2.7.0-67-g6704e78). An archive of the particular files which cause the problem is available [here](https://memeon.me/file/be91d45c1185d43f.tar.gz).

**Comment by mahkoh** [comment] 2016-03-19 10:06
The problem is that glibc's handling of CJK characters is broken. Those albums and tracks compare equal and due to various other bugs in cmus this causes the crash. I've created a branch [here](https://github.com/mahkoh/cmus/commit/d873a9efe718e7048b61acf6261c0396cdba5f8d) that removes collation and thus the problem from cmus.

**Comment by flyingmutant** [comment] 2016-03-19 13:37
@mahkoh, is there any open bug about glibc's broken CJK collation?

**Comment by mahkoh** [comment] 2016-03-19 13:42
I don't know. But maybe you remember that some time ago there was a bug related to Hangul characters and glibc. I opened a bug back then and nothing has happened yet. So I don't think that such a bug which doesn't seem to affect many programs will be fixed anytime soon.

One solution would be to use [ICU](http://site.icu-project.org/) instead of the POSIX functions. This could be an optional dependency so that glibc is used if ICU isn't installed (at compile time.)

**Comment by mahkoh** [comment] 2016-03-19 13:43
If ICU also uses the locale data provided by glibc then this won't work though (I think.)

**Comment by flyingmutant** [comment] 2016-03-19 14:00
Oh, I do remember that indeed now, thanks.

I am closing this as duplicate of #103. Regarding ICU — it might help, but it will effectively "fork" cmus installs in ICU-enabled and not. I am not sure I like that from the maintenance perspective (also, this is a departure from cmus' no-dependencies philosophy).

**Closed by flyingmutant** 2016-03-19 14:00 UTC
Labels: duplicate

**Comment by mahkoh** [comment] 2016-03-19 14:07
I don't think this issue should be closed. As it stands right now, OP cannot listen to his music in cmus which is certainly a serious cmus bug. Even if glibc returns an incorrect integer, this shouldn't cause cmus to crash. The related issue is closed too but wasn't as serious as this one.

**Comment by flyingmutant** [comment] 2016-03-19 14:29
Sound good – I've created a separate meta-issue #418 for that.
