### ISSUE TITLE
Keeps playing through internal speakers when connecting USB sound card

### ISSUE THREAD

**Issue by forthrin** [cmus/cmus#769] opened 2018-01-21 17:48 UTC
`cmus` keeps playing through internal speakers when connecting USB sound card.

1. Connect Mac to USB sound card (Duet).
1. Start `cmus` on MacBook Air.
1. Play music. (Music plays through sound card. GOOD.)
1. Disconnect sound card. (Music plays through internal speakers. GOOD.)
1. Reconnect sound card. (Music still plays through internal speakers. BAD!)

My `rc` file is empty (default settings).

---

1) `uname -a`:
```
Darwin skywalker 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus 61d4b2b
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/HEAD-61d4b2b_2/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/HEAD-61d4b2b_2/lib/cmus/op
  coreaudio
  ao
```

**Comment by Rhundom** [comment] 2018-02-02 04:37
It's because cmus isn't constantly checking / refreshing to look for a sound card whilst it is always refreshing / checking for internal speakers.

**Comment by forthrin** [comment] 2018-02-02 06:13
The problem happens when I'm *not* connected to the external speakers. I just mentioned this as a *possible* cause, but this is not directly provokable. The pattern feels more like:

1. Start `cmus`
1. Use it normally throughout the day.
1. Go to sleep. Get up in the morning. Go to the coffee shop.
1. Try to play music. BUG: `cmus` doesn't work anymore.

I realise this doesn't give much grounds for debugging if no-one else is experiencing the same thing. Anything I can do to provide more debug information?

**Comment by nefthy** [comment] 2019-02-05 13:50
@Wang-Yue ?

**Comment by nefthy** [comment] 2019-02-05 13:52
> The problem happens when I'm _not_ connected to the external speakers. I just mentioned this as a _possible_ cause, but this is not directly provokable. The pattern feels more like:
> 
> 1. Start `cmus`
> 2. Use it normally throughout the day.
> 3. Go to sleep. Get up in the morning. Go to the coffee shop.
> 4. Try to play music. BUG: `cmus` doesn't work anymore.
> 
> I realise this doesn't give much grounds for debugging if no-one else is experiencing the same thing. Anything I can do to provide more debug information?

this seems to be a separate issue.

**Comment by nefthy** [comment] 2019-02-05 15:00
duplicate of #653

**Closed by nefthy** 2019-02-05 15:00 UTC
Labels: MacOS, coreaudio
