### ISSUE TITLE
cmus: unrecognized option `--passwd'

### ISSUE THREAD

**Issue by daiyudong** [cmus/cmus#1335] opened 2024-05-31 06:56 UTC
cmus --listen 192.168.2.87 --passwd abc123
cmus: unrecognized option `--passwd'
---

1) `uname -a`:
```
FreeBSD www 14.0-RELEASE FreeBSD 14.0-RELEASE #0 releng/14.0-n265380-f9716eee8ab4: Fri Nov 10 05:57:23 UTC 2023     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64
```

2) `cmus --version`:
```
cmus v2.11.0
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue

Output Plugins: /usr/local/lib/cmus/op
  oss
  sndio
```

**Comment by jdholtz** [comment] 2024-06-12 01:00
I think this is a duplicate of #971. The flag is currently only checked for in `cmus-remote`, not `cmus`.

**Comment by daiyudong** [comment] 2024-06-14 07:40
> I think this is a duplicate of #971. The flag is currently only implemented in `cmus-remote`, not `cmus`.

![WX20240614-153602](https://github.com/cmus/cmus/assets/42144625/005ff03e-3362-4535-b638-6fec79dfe049)
man cmus
--passwd PASSWD
              Set the password for TCP/IP connections. Required if listening
              on host[:port]. Used in conjunction with --listen.

cmus: unrecognized option `--passwd'
cmus --passwd not working

**Closed** 2024-09-22 09:17 UTC
