### ISSUE TITLE
How to use album shuffle?

### ISSUE THREAD

**Issue by salutis** [cmus/cmus#1060] opened 2021-03-11 11:33 UTC
I would like `cmus` to choose some album (across my entire music library) and play it (*not* shuffling its tracks). Further, I would like to be able to advance the next (randomly chosen) album. Is this possible?

More technically, I would like to use `cmus` instead of the following script I wrote:

```bash
#!/bin/bash

PID=

abort() {
  echo
  echo "Aborting..."
  kill $PID
  exit
}

echo "Playing albums on shuffle."
echo "Press CONTROL-C to abort."

ls -1d */ \
  | sed 's|/$||g' \
  | sort -R \
  | while read DIR; do
    echo "$DIR"
    mpg123 --quiet --no-control "$DIR"/*.mp3 &
    PID=$!
    trap abort SIGINT
    wait $PID
done
```

---

1) `uname -a`:
```
Darwin Workstation.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

2) `cmus --version`:
```
cmus v2.9.1
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/Cellar/cmus/2.9.1/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  opus:
    Priority: 50
    File Types: opus
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  mp4:
    Priority: 50
    File Types: mp4 m4a m4b
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  aac:
    Priority: 50
    File Types: aac
    MIME Types: audio/aac audio/aacp
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  ffmpeg:
    Priority: 30
    File Types: aa aac ac3 aif aifc aiff ape au fla flac m4a m4b mka mkv mp+ mp2 mp3 mp4 mpc mpp ogg opus shn tak tta wav webm wma wv
    MIME Types:

Output Plugins: /usr/local/Cellar/cmus/2.9.1/lib/cmus/op
  coreaudio
```

**Comment by pgaskin** [comment] 2021-03-11 16:34
duplicate of #641 (PR #1045).

**Closed by pgaskin** 2021-03-11 16:34 UTC
