### ISSUE TITLE
Cmus freezes when playing Allegaeon's album "Elements Of The Infinite"

### ISSUE THREAD

**Issue by ghost** [cmus/cmus#847] opened 2018-12-21 23:06 UTC
1) `uname -a`:
```
Linux anarchy 4.19.8-300.fc29.x86_64 #1 SMP Mon Dec 10 15:23:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Distro is Fedora 29, since Fedora don't put that in uname.

2) `cmus --version`:
```
cmus v2.8.0-rc0-93-gf5a442a
Copyright 2004-2006 Timo Hirvonen
Copyright 2008-2016 Various Authors
```

3) `cmus --plugins`:
```
Input Plugins: /usr/local/lib/cmus/ip
  mad:
    Priority: 55
    File Types: mp3 mp2
    MIME Types: audio/mpeg audio/x-mp3 audio/x-mpeg
  vorbis:
    Priority: 50
    File Types: ogg oga ogx
    MIME Types: application/ogg audio/x-ogg
  modplug:
    Priority: 50
    File Types: mod s3m xm it 669 amf ams dbm dmf dsm far mdl med mtm okt ptm stm ult umx mt2 psm
    MIME Types:
  wav:
    Priority: 50
    File Types: wav
    MIME Types:
  cue:
    Priority: 50
    File Types:
    MIME Types: application/x-cue
  flac:
    Priority: 50
    File Types: flac fla
    MIME Types:
  wavpack:
    Priority: 50
    File Types: wv
    MIME Types: audio/x-wavpack
  mpc:
    Priority: 50
    File Types: mpc mpp mp+
    MIME Types: audio/x-musepack
  opus:
    Priority: 50
    File Types: opus
    MIME Types:

Output Plugins: /usr/local/lib/cmus/op
  pulse
  alsa
  oss
  jack
  ao
```

I know the title is oddly specific, but it's the only album I've noticed the issue with. Sometime through the album, usually on "Through Ages Of Ice - Otzi's Curse" (displayed as Through Ages Of Ice - Otzi<92>s Curse), the interface freezes. once the album finishes, it doesn't repeat despite Cmus being set to repeat the album. No input is processed, and I have to close the terminal window and reopen it to get Cmus working again.

**Comment by Ashymad** [comment] 2019-01-03 18:19
This happens if your tags have non-UTF encoding. Byte 0x92 is ’ (quotation mark) in windows-1252 encoding. It seems that cmus assumes UTF-8 encoding in tags, however 0x92 is not valid in UTF-8, which causes the freeze.

**Comment by PrimordialHelios** [comment] 2019-01-04 07:15
Fixed the name in the .cue file, and all is well! Should I leave this issue open, or is this something that won't be fixed?

**Comment by nefthy** [comment] 2019-02-06 23:23
I can't reproduce this by manualy adding a 0x92 character in a title in a cue file with 2.8.0

**Comment by amangrewal** [comment] 2019-02-07 18:11
I'm experiencing the same issue with any song that has invalid utf-8 in the tags. When the song starts playing, cmus hangs and eats up 100% of one cpu core.

What is happening is that cmus closes its d-bus connection, so the select function in main_loop returns -1, EBADF (Bad file descriptor).

I'm still investigating why cmus is closing that connection and how to stop it.

**Comment by nefthy** [comment] 2019-02-07 22:22
dbus might be a hint. I don't have that enabled. IIRC dbus uses xml for communication. Broken utf-8, could mean broken xml.

**Comment by amangrewal** [comment] 2019-02-13 21:25
So there seems to be two parts to this issue.

The first is that the dbus connection gets closed when invalid utf8 is sent. The solution to this is to translate invalid utf8 to \<xx\>, as is done everywhere else, before sending it on the bus.

The second is that if the call to ```select()``` in ```main_loop()``` results in an error, cmus freezes. I don't know if anything should be done about this. If we leave it as is, the user would have to ```kill -9``` cmus any time this happens. A second option would to be to not check the file descriptor anymore, i.e., continue running without any support for dbus. 

I'm leaning towards doing nothing but adding some ```d_print()``` statements in case the issue pops up again.

**Comment by nefthy** [comment] 2019-02-14 01:57
Thanks for narrowing this down. Both issues should be addressed, as any situation that requires `kill -9` is unacceptable. Would you like to submit PRs for this two points?

**Comment by amangrewal** [comment] 2019-02-14 02:23
I can submit a PR for the utf8/dbus issue within the week.

For the second issue, I don't really know what's the best way to address it. The options I see are

- Continue working without the closed fd
- Have ctrl-c/SIGINT be able to quit cmus, at least in exceptional cases
- cmus exits immediately

**Comment by nefthy** [comment] 2019-02-14 15:27
Hm, second issue needs a lot of though. The dbus connection can be closed by our peer at any time for any reason.

- Under which circumstances does that happen? Is a dbus restart enough?
- Can we recover at this point by reconnected? What if that also fails?
- Can we continue by just disabling dbus? Is that what the user would probably want?
- Are there other fd's that could fail in that select?

We could of course do a `BUG_ON(...)` but that seems to me, to be a bug waiting to happen.

**Comment by geek1011** [comment] 2019-02-14 16:37
These may be useful:
- https://wiki.ubuntu.com/DbusRestart
- systemd/systemd#2925
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805449

**Comment by alzee** [comment] 2020-10-13 07:27
Thanks for the PR

**Comment by pgaskin** [comment] 2024-09-22 22:52
Closing since #871 has been merged which fixes the immediate issue causing the DBus connection to close.

**Comment by pgaskin** [comment] 2024-09-22 22:53
A relevant trace for the DBus connection failure causing select problems:

```
(gdb) print mpris_fd
$1 = 9
(gdb) call (int)syscall(3, mpris_fd)
$2 = 0
(gdb) c
Continuing.
^C
Thread 1 "cmus" received signal SIGINT, Interrupt.
0x00007fd1291ffe57 in __GI___select (nfds=13, readfds=0x7ffd64b6d2d0, writefds=0x0, exceptfds=0x0, timeout=0x7ffd64b6d370) at ../sysdeps/unix/sysv/linux/select.c:69
69	  int r = SYSCALL_CANCEL (pselect6_time64, nfds, readfds, writefds, exceptfds,
(gdb) bt
#0  0x00007fd1291ffe57 in __GI___select (nfds=13, readfds=0x7ffd64b6d2d0, writefds=0x0, exceptfds=0x0, timeout=0x7ffd64b6d370) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x000000000044d08a in main_loop () at ui_curses.c:2289
#2  0x000000000044db84 in main (argc=1, argv=0x7ffd64b6d540) at ui_curses.c:2640
(gdb) step
__GI___pthread_disable_asynccancel (oldtype=oldtype@entry=0) at cancellation.c:63
Downloading source file /usr/src/debug/glibc-2.39-22.fc40.x86_64/nptl/cancellation.c
63      {                                                                                                                                                                                                
(gdb) bt
#0  __GI___pthread_disable_asynccancel (oldtype=oldtype@entry=0) at cancellation.c:63
#1  0x00007fd1291ffe69 in __GI___select (nfds=<optimized out>, readfds=0x7ffd64b6d2d0, writefds=<optimized out>, exceptfds=<optimized out>, timeout=0x7ffd64b6d370)
    at ../sysdeps/unix/sysv/linux/select.c:69
#2  0x000000000044d08a in main_loop () at ui_curses.c:2289
#3  0x000000000044db84 in main (argc=1, argv=0x7ffd64b6d540) at ui_curses.c:2640
(gdb) step
66	  if (oldtype & CANCELTYPE_BITMASK)
(gdb) step
62	__pthread_disable_asynccancel (int oldtype)
(gdb) step
__GI___pthread_disable_asynccancel (oldtype=0) at cancellation.c:71
71	  int oldval = atomic_load_relaxed (&self->cancelhandling);
(gdb) step
74	      newval = oldval & ~CANCELTYPE_BITMASK;
(gdb) step
76	  while (!atomic_compare_exchange_weak_acquire (&self->cancelhandling,
(gdb) step
83	  while (__glibc_unlikely ((newval & (CANCELING_BITMASK | CANCELED_BITMASK))
(gdb) step
__GI___select (nfds=<optimized out>, readfds=0x7ffd64b6d2d0, writefds=<optimized out>, exceptfds=<optimized out>, timeout=0x7ffd64b6d370) at ../sysdeps/unix/sysv/linux/select.c:71
71	  if (timeout != NULL)
(gdb) step
72	    TIMESPEC_TO_TIMEVAL (timeout, pts64);
(gdb) step
main_loop () at ui_curses.c:2290
warning: Source file is more recent than executable.
2290	
(gdb) bt
#0  main_loop () at ui_curses.c:2290
#1  0x000000000044db84 in main (argc=1, argv=0x7ffd64b6d540) at ui_curses.c:2640
(gdb) print rc
$3 = -1
```

**Closed by pgaskin** 2024-09-22 22:52 UTC
Labels: bug
